apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-compute-server-add-id-token-server-for-wif
patch: |-
  - op: add
    path: "/template/spec/volumes/-"
    value:
      name: webserver
      configMap:
       name: id-token-webserver-code
  - op: add
    path: "/template/spec/containers/-"
    value:
      command:
        - python
        - /app/id-token-webserver.py
      env:
      - name: SAS_REFRESH_LIFE
        value: "3600"
      - name: SAS_REFRESH_EXECUTABLE
        value: /opt/sas/viya/home/bin/refresh
      - name: SAS_REFRESH_CONFIG_LOG_LEVEL
        value: TRACE
      envFrom:
      - secretRef:
          name: sas-consul-client
      image: <YOUR_CHAINGUARD_IMAGE_WITH_SHA>
      imagePullPolicy: IfNotPresent
      name: id-token-wif
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 50Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /tmp
        name: tmp
      - mountPath: /config
        name: config
      - mountPath: /security
        name: security
      - name: webserver
        mountPath: /app/id-token-webserver.py
        subPath: id-token-webserver.py
target:
  kind: PodTemplate
  name: sas-compute-job-config
